# No TABs allowed in this file. None. Your editor may try to insert some.
# Beware, this is YAML and YAML CARES. A LOT. (too much)
site_name: JHPCE
site_url: https://jhpce.jhu.edu/
nav:
  - Home:
    - index.md
    - About Us:
      - JHPCE Model: aboutus/model.md
      - Staff: aboutus/staff.md
      - JHPCE Constitutional Principles: aboutus/principles.md
      - Grant and Acknowledgment Blurbs: aboutus/GrantAndAckBlurbs.md
    - Getting Started:
      - joinus/index.md
      - Getting Started Overview: joinus/index.md
      - New user form: joinus/new-users-form.md
      - New PI information and form: 
         - New PI Information: joinus/new-pi.md
         - New PI Form: joinus/new-pi-form.md
      - Orientation/Logging In:
        - Overview: orient/orientation-overview.md
        - JHPCE Orientation (PDF download): https://docs.google.com/presentation/d/1elMSTUdKws7FLVFK7vVV_AErA4brNSPX/export/pdf
        - C-SUB Orientation (PDF): orient/images/latest-csub-orient.pdf
      - Leaving JHPCE as a User or PI: joinus/leaving.md
      - New C-SUB PI or user?: csub/new-csub-users.md
      - Policies: joinus/policies.md
      - HIPAA on JHPCE: joinus/hipaa.md
    - Getting Help:
      - Basics: help/help-basics.md
      - Submitting Good Queries: help/good-query.md
      - Support Email List Archives: help/list-archives.md
      - External Guides: help/external.md
      - Glossary: help/glossary-manual.md
      - Tagged Files: ourtools/tags.md
      - How to read a manual page (pdf): help/images/guide-to-manual-pages.pdf
      - Tools For Site Developers: 
         - Handy Features: ourtools/features.md
         - Tips & Conventions: ourtools/tips-conventions.md
         - Wishlist: ourtools/wishlist.md
    - FAQ: help/faq.md
    - Accessing the cluster:
      - Overview: access/access-overview.md
      - SSH: access/ssh.md
      - X11: access/x11.md
      - MobaXterm: access/mobaxterm.md
      - Transferring files in or out: 
        - Overview: access/file-transfer.md
        - Globus: access/globus.md
        - OneDrive via rclone: access/onedrive.md
    - Managing Files:
      - Files Overview: files/files-overview.md
      - Sharing Files: files/sharing-files.md
      - ACL: files/acl.md
      - Copying within cluster: files/copying-files.md
      - "Rsync: A Key File Mgmt Tool":
        - Using Rsync: files/rsync.md
        - Itemize Output Key: files/rsync-itemize-table.md
        - Itemize Manual Page: files/rsync-itemize-manpage.md
      - Archive Files: files/archive-files.md
      - Navigating Deep Directory Trees: files/deep-paths.md
      - Data Security: files/data-security.md
      - Encrypting filesystems with ENCFS: files/encfs.md
      - Storage Tips: storage/storage-tips.md
      - Copying within cluster: files/copying-files.md
    - Storage Policies and Practices: 
      - storage/index.md
      - Storage Overview: storage/index.md
      - Backups and Restores: storage/backups-restores.md
      - Quotas: storage/quotas.md
      - Fastscratch: storage/fastscratch.md
      - Storage Tips: storage/storage-tips.md
    - Software:
      - Overview: sw/sw-overview.md
      - Local Software:
        - Matlab: sw/matlab.md
        - Python: sw/python.md
        - R and RStudio: sw/r-n-friends.md
        - SAS: sw/sas.md
        - Stata: sw/stata.md
      - Modules: sw/modules.md
      - Installing Your Own:
        - Compile from Source: sw/building-from-src.md
        - Conda Environment: sw/conda.md
        - Python Packages: sw/python-pkg.md
        - R Packages: sw/r-pkg.md
#        - Singularity: sw/singularity.md
      - JHPCE-created: sw/locally-written.md
      - Helpful GUI Programs: sw/gui-tools.md
    - Job scheduler (SLURM): 
      - Getting Started: slurm/getting-started.md
      - About Jobs: slurm/about-jobs.md
      - Partitions: slurm/partitions.md
      - Memory Usage: slurm/ram.md
      - Time Limits: slurm/time-limits.md
      - "Command tips & reference":
        - "Cmd tips & reference": slurm/slurm-commands-ref.md
        # - reportseff tips: slurm/tips-reportseff.md
        - sacct tips: slurm/tips-sacct.md
        - sacctmgr tips: slurm/tips-sacctmgr.md
        - scontrol tips: slurm/tips-scontrol.md
        - squeue tips: slurm/tips-squeue.md
        - reportseff tips: slurm/tips-reportseff.md
      - Interactive Jobs: slurm/interactive-jobs.md
      - Crafting Batch Jobs: slurm/crafting-jobs.md
      - Monitoring Your Jobs: slurm/monitoring.md
      - When Will My Job Start?: slurm/whenstart.md
      - Quality of Service (QOS): slurm/qos.md
      - Job Environment: slurm/environment.md
      - Node Features: slurm/node-features.md
      - Example User Guides: slurm/user-guide-collection.md
      - SLURM FAQ: slurm/slurm-faq.md
    - User Guides/Tutorials:
      - GPU: 
        - Using GPUs on JHPCE: gpu/gpu-info.md
        - Alphafold: gpu/alphafold.md
      - VS Code: sw/vscode.md
      - Cost Calculator: help/cost-calculator.md
    - Web Portal:
      - GUI Applications: portal/web-apps.md
      - Datacatalog: portal/datacatalog.md
      - Self Service MFA, Password Requests : portal/web-reset.md
    - C-SUB:
      - What Is The C-SUB?: csub/csub-overview.md
      - New User: csub/new-csub-users.md
      - C-SUB Orientation (PDF): orient/images/latest-csub-orient.pdf
# Example of three-level topic syntax
#   - Storage:
#     - slurm/index.md
#     - PI Subtopic1: acl.md
#     - PI Subtopic2: help.md
#     - Third PI topic:
#       - sw/README.md
#       - PI Subtopic4: acl.md
#       - PI Subtopic5: storage.md
theme: 
  name: material
  custom_dir: overrides
  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/#changing-the-logo-and-icons
  logo: images/sph-logo.svg
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  navigation_depth: 4
  features:
    #- navigation.expand # works. do we want it or not? NO
    #- toc.integrate # do not want this. prevents right side TOC
    # this does not work because it is an "insiders" feature
    #- navigation.path # does not work. even with 3 levels of depth
    - navigation.sections # vital
    - toc.follow # investigate this. want?
    - announce.dismiss # announcement can be dismissed
    - navigation.top # works. Displays "Back to top" button when one scrolls upwards
    - header.autohide # hides header if scroll far enough down. More content visable
    - navigation.footer # provides place to display copyright
    #indexes:
    #   Do you want a topic header line to represent a document?
    #   If this is enabled, you can, BUT IT HAS TO BE NAMED index.md (or README.md)
    #   Whether it is defined or not, you are NOT allowed to specify a document
    #   for ANY level of topic header line, e.g.   - topicname: doc.md
    #   These are valid:
    #       - Home:
    #         - index.md
    #   or this:
    #       - SomeSubject:
    #         - slurm/index.md
    #   or this:
    #       - OtherSubject:
    #         - slurm/README.md
    - navigation.indexes
    # code blocks - https://squidfunk.github.io/mkdocs-material/reference/code-blocks/
    #    there are lots of customizations and info there, not just about the
    #    following feature. e.g. a list of language types https://pygments.org/docs/lexers/
    - content.code.copy # allow users to copy code blocks via button on right
    # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#adding-annotations
    - content.code.annotate # Allow annotations inside blocks after comment chars
#
# Plugins
#
# If you add a plugin, update the mkdocs recipe in the features.md
#
# ROUGHLY ALPHABETICAL by topic
#
# https://squidfunk.github.io/mkdocs-material/plugins/
plugins:
  # https://timvink.github.io/mkdocs-git-authors-plugin/index.html
  # AUTHORSHIP
  - git-authors:
      enabled: true
      show_contribution: true
      authorship_threshold_percent: 33
      fallback_to_empty: true
  # BLOG
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/
  # Be aware that you cannot use features preceeded by "Insiders"
  #- blog
  - git-revision-date-localized # this forces you to work in a git cloned repo
  # If you are not, then everything breaks until you comment out this plugin.
  - open-in-new-tab
  # SEARCH
  # search is enabled by default but if you add options it HAS TO BE LISTED
  # there are A LOT of extras you can do. Someone explore later if desired.
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/
  - search
  # Adi added extract_listings 20240401
  # https://github.com/six-two/mkdocs-extract-listings-plugin
  - extract_listings:
      listings_file: all-listings.md
      placeholder: JHPCE_PLACEHOLDER_FOR_THE_LISTINGS_PLUGIN
      javascript_search_file: javascripts/listing-search.js
  # JRT added https://timvink.github.io/mkdocs-table-reader-plugin/
  - table-reader
  # TAGS
#  - tags:
#      tags_file: ourtools/tags.md

#
# Python MarkDown Extensions
#
# https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/
# But sometimes you may need more detailed info, in which case you go to this
# URL: https://facelessuser.github.io/pymdown-extensions/
markdown_extensions:
  # JRT says following three lines are ALL needed to enable admonition
  # Then to the superfences line I added the info needed for mermaid 
  # Mermaid: This was added to superfences to enable simple diagrams & charting
  # https://squidfunk.github.io/mkdocs-material/reference/diagrams/?h=mermaid#diagrams
  - admonition
  - pymdownx.superfences: # allows for arbitrary nesting of content blocks
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details # makes the resulting admonitions call-outs collapsible
  - pymdownx.tabbed: # enables tabs
      alternate_style: true
  - abbr # Abbreviations and optional glossery
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#attribute-lists
  - attr_list # Enable addition of HTML to almost any kind of Markdown element
  - def_list # Definition lists
  - footnotes
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#markdown-in-html
  # https://squidfunk.github.io/mkdocs-material/reference/grids/
  - md_in_html # added to support grids for the home page. related to attr_list
  - tables
  # TABLE OF CONTENTS
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#table-of-contents
  - toc:
      toc_depth: 5 # optional
      permalink: true # Adds anchor link to each section of a doc
      permalink_title: Anchor link to this section for reference # Adds phrase if you hover 
  - pymdownx.caret # enables certain text formatting https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#caret-mark-tilde
  - pymdownx.mark # enables certain text formatting https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#caret-mark-tilde
  - pymdownx.tilde # enables certain text formatting https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#caret-mark-tilde
  - pymdownx.critic # https://squidfunk.github.io/mkdocs-material/reference/formatting/#highlighting-changes
  # following four lines needed to enable (some) icons & emojis
  # https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      linenums: false # add line numbers to code blocks by default? (to enable when desired
                     # add linenums="1" after the initial three backticks)
  - pymdownx.inlinehilite
  - pymdownx.keys # keyboard meta keys displayed e.g. ++ctrl++
  # To include a file you have to specify the full relative path to it starting inside of
  # docs/ and define base_path: docs
  - pymdownx.snippets: # adds the ability to embed content from arbitrary files into a document
      check_paths: false # if true, if snippets cannot be found, the site cannot be rebuilt!!!
      base_path: docs
  - pymdownx.tasklist:
      custom_checkbox: true
#
# FOOTER-RELATED SETTINGS (other than the req'd features:navigation.footer)
copyright: Copyright &copy; 2024 - 2028 Joint JHPCE Exchange
#
extra:
  generator: false # do not display "Made with Material for MkDocs"
  analytics:
    provider: google
    property: G-G0LK68FDTM
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://github.com/jhpce-jhu/jhpce_mkdocs/discussions/categories/website-feedback" target="_blank" rel="noopener">website feedback forum</a>.
# hide footer in specific pages with these instructions:
# https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/#hiding-prevnext-links
#
# EXCLUDE FILES OR DIRECTORIES
# This follows the .gitignore pattern format
# (https://www.mkdocs.org/user-guide/configuration/#exclude_docs)
# (https://git-scm.com/docs/gitignore#_pattern_format)
exclude_docs: drafts
#
# https://www.mkdocs.org/user-guide/configuration/#validation
validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
#
#
#
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
extra_css:
  - stylesheets/extra.css
